# Project identification
sonar.projectKey=Erik-McS_MicroControl
sonar.projectName=microcontrol

# Where your source code lives
sonar.sources=src

sonar.organization=erik-mcs

# Tell SonarQube to look for C files
sonar.c.file.suffixes=.c,.h

# This tells the scanner where to find the build logs (crucial for C)
sonar.cfamily.build-wrapper-output=bw-output

